"""initial multi-tenant schema

Revision ID: 652c888efd62
Revises: 
Create Date: 2026-04-06 17:06:40.188654
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652c888efd62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='plantype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_tenant_id'), 'webhook_logs', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'blocked', name='conversationstatus'), nullable=False),
    sa.Column('is_ai_active', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_phone_number'), 'conversations', ['phone_number'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_index('ix_conversations_tenant_phone', 'conversations', ['tenant_id', 'phone_number'], unique=True)
    op.create_table('tenant_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=False),
    sa.Column('business_address', sa.String(length=500), nullable=False),
    sa.Column('business_phone', sa.String(length=50), nullable=False),
    sa.Column('business_website', sa.String(length=300), nullable=False),
    sa.Column('business_hours', sa.JSON(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_tone', sa.String(length=50), nullable=False),
    sa.Column('use_cases', sa.JSON(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('fallback_message', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('knowledge_base', sa.Text(), nullable=False),
    sa.Column('whatsapp_provider', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_credentials', sa.JSON(), nullable=False),
    sa.Column('webhook_secret', sa.String(length=100), nullable=False),
    sa.Column('ai_provider', sa.String(length=20), nullable=False),
    sa.Column('ai_api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('ai_model', sa.String(length=50), nullable=False),
    sa.Column('external_api_config', sa.JSON(), nullable=False),
    sa.Column('custom_tools', sa.JSON(), nullable=False),
    sa.Column('is_setup_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_configs_tenant_id'), 'tenant_configs', ['tenant_id'], unique=True)
    op.create_table('usage_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('messages_received', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('ai_tokens_input', sa.Integer(), nullable=False),
    sa.Column('ai_tokens_output', sa.Integer(), nullable=False),
    sa.Column('whatsapp_api_calls', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_tenant_date', 'usage_tracking', ['tenant_id', 'date'], unique=True)
    op.create_index(op.f('ix_usage_tracking_date'), 'usage_tracking', ['date'], unique=False)
    op.create_index(op.f('ix_usage_tracking_tenant_id'), 'usage_tracking', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_tenant_created', 'messages', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index('ix_messages_tenant_created', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_tracking_tenant_id'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_date'), table_name='usage_tracking')
    op.drop_index('ix_usage_tenant_date', table_name='usage_tracking')
    op.drop_table('usage_tracking')
    op.drop_index(op.f('ix_tenant_configs_tenant_id'), table_name='tenant_configs')
    op.drop_table('tenant_configs')
    op.drop_index('ix_conversations_tenant_phone', table_name='conversations')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_phone_number'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_webhook_logs_tenant_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
